image: vikko00/mpet-deps:latest

pipelines:
  pull-requests:
    'development':
      - step:
          script:
            - cd bin
            - ./mpetruntests.sh development
            - cd ../tests
            - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
    'master':
      - step:
          script:
            - cd bin
            - ./mpetruntests.sh master
            - cd ../tests
            - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
  branches:
    'master':
      - step:
          script:
            - cd bin
            - ./mpetruntests.sh stable
            - cd ../tests
            - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
