image: vikko00/mpet-deps:latest

pipelines:
  default:
    - step:
        script:
          - cd bin
          - ./mpetruntests.sh
          - cd ../tests
          - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
          - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
