image: vikko00/mpet-deps:latest

pipelines:
  default:
    - step:
        script:
          - cd bin && ./mpetruntest.sh
          - cd tests && pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
          - cd tests && pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
