image: vikko00/daetools:1.9.0
options:
 docker: true

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - docker
          script:
            - pip install .[test]
            - cd bin
            - export COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
            - ./mpetruntests.sh $BITBUCKET_PR_DESTINATION_BRANCH
            - cd ../tests
            - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified timings_tests.py || true #Ok to fail for now
  branches:
    'master':
      - step:
          caches:
            - docker
          script:
            - pip install .[test]
            - cd bin
            - export COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
            - ./mpetruntests.sh stable
            - cd ../tests
            - pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py
            - pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified timings_tests.py || true #Ok to fail for now
