name: MPET docker CI

on:
  pull_request:
    branches: [ master,development ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    container:
      image: vikko00/mpet-deps:latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: mpet
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: base-mpet
        ref: ${{ github.base_ref }}
    - name: Set up test for modified branch
      run: |
        cd mpet/bin
        rm -rf workdir
        mkdir workdir
        cd workdir

        cp ../run_tests.py .
        ln -s ../../mpet .
        ln -s ../../tests .

    - name: run tests for modified branch and get coverage
      run: |
        cd mpet/bin/workdir
        coverage run --source=../../mpet/ run_tests.py ../../bin/workdir/modified > /dev/null

    - name: upload Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd mpet/bin/workdir
        coveralls || : #Dont fret if if fails

    - name: run tests for base branch
      run: |
        cd mpet/bin/workdir
        ln -sf ../../../base-mpet/mpet .
        python run_tests.py ../../bin/workdir/stable > /dev/null

    - name: Checks test results
      run: |
        cd mpet/tests
        pytest --baseDir=ref_outputs           --modDir=../bin/workdir/modified compare_tests.py
        pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified compare_tests.py

    - name: Check Timings
      run: |
        cd mpet/tests
        pytest --baseDir=../bin/workdir/stable --modDir=../bin/workdir/modified timings_tests.py || true #Ok to fail for now
